// Generated by CoffeeScript 1.9.3
(function() {
  var THRESHOLD, child, e, err, fs, i, instance, instances, len, stats;

  fs = require('fs');

  child = require('child_process');

  THRESHOLD = 250;

  e = child.execSync;

  instances = fs.readdirSync('./instances');

  e("make");

  for (i = 0, len = instances.length; i < len; i++) {
    instance = instances[i];
    if (!(Number(instance.match(/^vars-(\d{3})-.*\.cnf$/)[1]) <= THRESHOLD)) {
      continue;
    }
    try {
      e("picosat < instances/" + instance + " > stats.txt");
    } catch (_error) {
      err = _error;
    }
    stats = fs.readFileSync("./stats.txt", "utf-8");
    console.log(instance);
    console.log("------------------");
    console.log(stats);
  }

  e("rm -f ./stats.txt");

}).call(this);
